#!/bin/bash

# Start a docker container running Spotify
# Based on syncomm's
# Usage:
#	./docker-spotify &
#
red='\e[1;31m'
green='\e[1;31m'
purp='\e[1;35m'
cyan='\e[1;36m'
yellow='\e[1;33m'
NC='\e[0m'

echo -e "${purp}Getting host's X11 cookie${NC}"
XCOOKIE=`xauth list | grep unix | cut -f2 -d"/" | tr -cd '\11\12\15\40-\176' | sed -e 's/  / /g'`

if [ ! -e /tmp/.spotify-pulse-socket ];
then
    echo -e "${purp}Adding Pulseaudio socket at /tmp/.spotify-pulse-socket${NC}" 
    SPOTIFYSOCKET=`pactl load-module module-native-protocol-unix auth-anonymous=1 socket=/tmp/.spotify-pulse-socket`
fi

echo -e "${purp}Starting Spotify container${NC}"
echo docker run --rm --name spotify \
     	    	-e XCOOKIE=\'$XCOOKIE\' \
		-e DISPLAY=\'unix$DISPLAY\' \
		-v /tmp/.X11-unix/:/tmp/.X11-unix/ \
		-v /tmp/.spotify-pulse-socket:/tmp/.spotify-pulse-socket \
		spotify | bash

echo -e "${purp}Removing Pulseaudio socket at /tmp/.spotify-pulse-socket${NC}" 
pactl unload-module $SPOTIFYSOCKET

exit 0
